language: node_js
node_js: node
cache: yarn
jobs:
  include:
    - stage: Test
      install: yarn install --frozen-lockfile
      before_script: yarn build
      script:
        - yarn test
        - yarn size
    - stage: Release
      if: tag =~ ^v[0-9]
      install: yarn install --frozen-lockfile
      before_script: yarn build
      script:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        - node scripts/publish.js
