language: node_js
node_js: node
cache: yarn
jobs:
  include:
  - stage: Test
    env:
    - TEST_ENV=cjs BUILD_ENV=cjs
    - TEST_ENV=umd BUILD_ENV=umd
    - TEST_ENV=source
    before_script:
    # react-router ESM build is imported by react-router-dom UMD,
    # so we need to build it before building react-router-dom UMD
    - ([[ "$BUILD_ENV" != "umd" ]] || (cd packages/react-router && BUILD_ENV=esm yarn build))
    - ([[ -z "$BUILD_ENV" ]] || yarn build)
    # react-router CJS build is imported by react-router-config tests,
    # so we need to build it before running react-router-config tests
    - ([[ "$BUILD_ENV" = "cjs" ]] || (cd packages/react-router && BUILD_ENV=cjs yarn build))
    script: yarn test
  - stage: Release
    if: tag =~ ^v[0-9]
    before_script: yarn build
    script: echo "Publishing $TRAVIS_TAG to npm ..."
    before_deploy: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > "$HOME/.npmrc"
    deploy:
      provider: script
      script: lerna publish from-git --yes --pre-dist-tag next
      skip_cleanup: true
      on:
        tags: true
  - stage: Deploy Website
    if: branch = website
    env: PUBLIC_PATH=/react-router/
    before_script: yarn build
    script: echo "Deploying website to https://reacttraining.com$PUBLIC_PATH"
    before_deploy:
    - openssl aes-256-cbc -K $encrypted_70c5e56b421c_key -iv $encrypted_70c5e56b421c_iv
      -in website_deploy_key.enc -out website_deploy_key -d
    - chmod 600 website_deploy_key
    - eval $(ssh-agent -s)
    - ssh-add website_deploy_key
    deploy:
      provider: script
      script: bash scripts/deploy-website.sh
      skip_cleanup: true
      on:
        branch: website
